### ISSUE TITLE
[IMPROVEMENT] OPTIMIZE DENDRO FOR PROJECT Multicamera systems in dendro prd

### ISSUE THREAD

**Issue by NelsonPereira1991** [feup-infolab/dendro#331]
### Dendro Version if known (or site URL)
master

### Please describe the expected behaviour
Users should be able to navigate Multicamera systems folders and files, and add and save descriptors quickly.

### Please describe the actual behaviour
This specific project is quite complex and has many sub-folders and files with per folder descritors. Dendro is taking a bit longer when the user is navigating between folders and also when saving descriptors.

### What steps can be taken to reproduce the issue? 
Navigate in the project Multicamera systems in the dendro-prd instance, and try to fill in descriptors.,

### Possible ways to fix the problem (programmers)
Optimize code related to the get metadata and save metadata functions.

**Comment by silvae86** [comment]
I thought this was fixed. At the time I tried to remove the recursive evaluation of Metadata quality, but there must be still a recursive call somewhere in the code.                                                                                                                                                                         Sent via the BlackBerry Hub for Android                                                                                                                                                                           From: notifications@github.comSent: January 29, 2018 10:10 AMTo: dendro@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [feup-infolab/dendro] [IMPROVEMENT] OPTIMIZE DENDRO FOR PROJECT Multicamera systems in dendro prd (#331)  Dendro Version if known (or site URL)
master
Please describe the expected behaviour
Users should be able to navigate Multicamera systems folders and files, and add and save descriptors quickly.
Please describe the actual behaviour
This specific project is quite complex and has many sub-folders and files with per folder descritors. Dendro is taking a bit longer when the user is navigating between folders and also when saving descriptors.
What steps can be taken to reproduce the issue?
Navigate in the project Multicamera systems in the dendro-prd instance, and try to fill in descriptors.,
Possible ways to fix the problem (programmers)
Optimize code related to the get metadata and save metadata functions.

**Comment by NelsonPereira1991** [comment]
I think it is fixed now. Maybe it was due to a merge error ?
